dependencies:
  - pip:
      - azure-storage-file-datalake==12.16.0
      - azure-keyvault-secrets==4.9.0
      - azure-storage-blob==12.25.1
      - azure-schemaregistry-avroencoder==1.0.0
      - azure-eventhub==5.15.0
      - azure-identity==1.23.0
      - azure-mgmt-eventhub==11.2.0
      - azure-schemaregistry==1.3.0
      - azure-monitor-opentelemetry-exporter==1.0.0b36
      - faker==37.3.0
      - icalendar==6.3.1
